Issue 33 & Issue 32
ConstanzaFrutos/micava pull request #57
Opened 2021-08-14 15:36 UTC by julimej

#33 
#32

2021-08-14 17:41 UTC, jomedina96 commented
![Screenshot from 2021-08-14 14-39-13](https://user-images.githubusercontent.com/17090039/129455756-94e97761-c724-411a-8896-02d078a08273.png)

Localmente me esta tirando error, el meno de historial de compra deberia aparecer solamente si no estoy logeado, y ademas hacerlo safenull

2021-08-14 19:01 UTC, ConstanzaFrutos commented
> ![Screenshot from 2021-08-14 14-39-13](https://user-images.githubusercontent.com/17090039/129455756-94e97761-c724-411a-8896-02d078a08273.png)
> 
> Localmente me esta tirando error, el menu de historial de compra deberia aparecer solamente si no estoy logeado, y ademas hacerlo safenull

Por que solo si no estas logueado? Deberia ser al reves, si estas logueado

2021-08-15 04:05 UTC, jomedina96 commented
> > ![Screenshot from 2021-08-14 14-39-13](https://user-images.githubusercontent.com/17090039/129455756-94e97761-c724-411a-8896-02d078a08273.png)
> > Localmente me esta tirando error, el menu de historial de compra deberia aparecer solamente si no estoy logeado, y ademas hacerlo safenull
> 
> Por que solo si no estas logueado? Deberia ser al reves, si estas logueado

jaja tenes razon, lo dije al reves. Sorry

2021-08-15 04:43 UTC, jomedina96 requested changes

2021-08-15 04:43 UTC, jomedina96 commented on front/web/src/app/components/Historial/Detalle/Botella.js
> +    <div className={classes.root}>
No esta bueno copiar el objeto de Marketplace, utilizar el objeto de marketplace

2021-08-15 16:22 UTC, ConstanzaFrutos commented
![image](https://user-images.githubusercontent.com/30637772/129485064-643640f1-35a2-42f1-a6d9-fc107aa8be58.png)

Cambie el tamaño de esto porque el subtitulo no se veia y e titulo era demasiado grande. Si podes intenta que el texto cuando no tenes vinos quede alineado, sino o pasa nada.

![image](https://user-images.githubusercontent.com/30637772/129485186-e90712cc-11dd-4852-9806-c33064c73658.png)

Lo mismo aca.

![image](https://user-images.githubusercontent.com/30637772/129485228-baebde66-3907-4af4-9bd9-5dc424a9478a.png)

Y le subi un poco la fuente a esta.

Si no les gusta volvemos el commit para atras.

2021-08-15 21:55 UTC, julimej commented on front/web/src/app/components/Historial/Detalle/Botella.js
> +    <div className={classes.root}>
Esto esta opcional agregado el objeto

2021-08-15 22:42 UTC, ConstanzaFrutos approved these changes

2021-08-15 22:43 UTC, merged