Feature/subastas page
ConstanzaFrutos/micava pull request #60
Opened 2021-08-16 07:25 UTC by jomedina96

2021-08-16 20:49 UTC, seblaz requested changes
Buenas, dejo unos comentarios

2021-08-16 20:49 UTC, seblaz commented on front/web/src/app/subastas/screens/Home.js
> +        </Grid>
Son necesarios los filtros? En caso de que sí no está bueno copiar y pegar, sino reutilizar los anteriores, sobre todo teniendo en cuenta que los filtros del marketplace se mejoraron mucho y los que se copiaron son los viejos

2021-08-16 20:49 UTC, seblaz commented on front/web/src/app/components/Subasta/index.js
> +export default Subasta;
Este componente no aporta nada

2021-08-16 20:49 UTC, seblaz commented on front/web/src/app/components/Subasta/Cuerpo.js
> +  // eslint-disable-next-line no-unused-vars
No es necesario deshabilitar este warning

2021-08-16 20:49 UTC, seblaz commented on front/web/src/app/components/Subasta/Cuerpo.js
> +      })
Corregir por `'Debés estar logueado para pagar una subasta'`. De todas formas, por qué me aparece el botón de pagar si no estoy logueado?

2021-08-16 20:49 UTC, seblaz commented on front/web/src/app/components/Subasta/Cuerpo.js
> +    return false;
Corregir el mensaje

2021-08-16 20:49 UTC, seblaz commented on front/web/src/app/components/Subasta/Cuerpo.js
> +      }
Es mejor solo permitir que se ingresen números

2021-08-16 20:49 UTC, seblaz commented on front/web/src/services/SubastasService.js
> +    // query += `&price.amount_gte=${rangoPrecios[0]}&price.amount_lte=${rangoPrecios[1]}`;
Parece que los filtros no tienen efecto, entonces para qué están?

2021-08-16 20:49 UTC, seblaz commented on front/web/src/app/components/Subasta/Cuerpo.js
> +              </Button>
Habría que agregar algo para darle feedback al usuario y que no toque el botón varias veces, al igual que en el botón de "Ir al pago" del carrito.

2021-08-16 20:49 UTC, seblaz commented on back/mercadopago.js
> +
Hay algunos problemas con el back:
- Se repite bastante código con el pago del marketplace. Estaría bueno sacarlo a una función aparte y reutilizarlo.
- Como la redirección luego del pago en mercadopago se hace al mismo endpoint que el pago del marketplace se generan varios errores. El primero es que el formato de lo que se guarda en la variable `preferences` es distinto, con lo cual el back rompe. El segundo es que no se actualiza el estado de la subasta luego de ser pagada.

2021-08-16 20:49 UTC, seblaz commented on front/web/src/app/components/Subasta/Cuerpo.js
> +        ofertarSubasta({ ...subasta, highestBid: parseInt(bid), ownerOfHighestBid: 'Sebastián' })
`ownerOfHighestBid: 'Sebastián'`: Sería mejor utilizar el email, dado que no tenemos el nombre

2021-08-16 20:49 UTC, seblaz commented on front/web/src/app/components/Subasta/Botella.js
> +
Este archivo no se usa en ningún lado

2021-08-16 20:49 UTC, seblaz commented on front/web/src/app/components/Subasta/DatosResumidos.js
> +
Este archivo no se usa en ningún lado

2021-08-16 20:49 UTC, seblaz commented on front/web/src/app/components/Subasta/Precio.js
> +import { makeStyles } from '@material-ui/core/styles';
Este archivo no se usa en ningún lado

2021-08-16 20:49 UTC, seblaz commented on front/web/src/app/components/Subasta/StyledRating.js
> +import { Rating } from '@material-ui/lab';
Este archivo solo se usa en Valoraciones, que a su vez no se usa en ningún lado

2021-08-16 20:49 UTC, seblaz commented on front/web/src/app/components/Subasta/Valoraciones.js
> +import { makeStyles } from '@material-ui/core/styles';
Este archivo no se usa en ningún lado

2021-08-16 20:49 UTC, seblaz commented on front/web/src/app/index/sections.js
> +const sections = [Marketplace, Bodega, Cava, Subastas, Historial];
Creo que es mejor ponerlo después de Bodega

2021-08-16 20:49 UTC, seblaz commented on front/web/src/app/subastas/components/Carrito/BotonCerrar.js
> +import CloseIcon from '@material-ui/icons/CloseRounded';
Hay unos cuantos archivos en esta carpeta `app/subastas/components/Carrito` que no se usan en ningún lado

2021-08-16 20:49 UTC, seblaz commented on front/web/src/app/subastas/index.js
> +};
Sería mejor poner un título en el medio y el logo a la derecha, al igual que en las cajas mensuales

2021-08-16 22:57 UTC, jomedina96 commented on front/web/src/app/components/Subasta/Cuerpo.js
> +        ofertarSubasta({ ...subasta, highestBid: parseInt(bid), ownerOfHighestBid: 'Sebastián' })
hm pero que mostrariamos en "Mayor apostador" no tenemos el nombre guardado

2021-08-16 23:42 UTC, jomedina96 commented on front/web/src/app/components/Subasta/Cuerpo.js
> +              </Button>
hay algo asi implementado en otra parte de la aplicacion?

2021-08-16 23:43 UTC, jomedina96 commented on front/web/src/app/components/Subasta/Cuerpo.js
> +      })
tema de implementacion, pero se podria sacar si aporta valor

2021-08-16 23:58 UTC, jomedina96 commented on back/mercadopago.js
> +
imo el codigo de repetido es lo de menos dado que tenemos el deadline ensima, y el proyecto tiene deadline el miercoles, pero lo otro lo corrigo

2021-08-18 00:56 UTC, seblaz commented on front/web/src/app/components/Subasta/Cuerpo.js
> +    return false;
@jomedina96 Donde dice 'Debés estar logueado para ofertar una subscripción' debería decir algo del estilo 'Debés estar logueado para ofertar', dado que no son subscripciones estas

2021-08-18 01:07 UTC, seblaz approved these changes
LGTM!

2021-08-18 01:07 UTC, merged